"""delete_sku_stock

Revision ID: 1651f4cfdc3e
Revises: ee949af06bdb
Create Date: 2026-06-18 09:50:44.023914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1651f4cfdc3e'
down_revision: Union[str, Sequence[str], None] = 'ee949af06bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
