"""sku_add_stock

Revision ID: dcaa229114a8
Revises: 1651f4cfdc3e
Create Date: 2026-06-18 10:04:50.108568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcaa229114a8'
down_revision: Union[str, Sequence[str], None] = '1651f4cfdc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'stock')
    # ### end Alembic commands ###
